"""
Patient ID encryption using Fernet symmetric encryption.
- Encrypt before storing / sending to LLM.
- Decrypt only when explicitly needed (e.g. PDF rendering).
- The key is loaded from PATIENT_ENCRYPT_KEY in .env
  If not set, a stable key is derived from JWT_SECRET so existing envs still work.
"""
import os
import base64
import hashlib
from pathlib import Path

from cryptography.fernet import Fernet
from dotenv import load_dotenv

load_dotenv(dotenv_path=Path(__file__).parent.parent / ".env")


def _get_fernet() -> Fernet:
    """Return a Fernet instance using the configured key."""
    raw_key = os.getenv("PATIENT_ENCRYPT_KEY")

    if raw_key:
        # Expect a URL-safe base64-encoded 32-byte key (generated by Fernet.generate_key())
        key = raw_key.encode()
    else:
        # Derive a stable 32-byte key from JWT_SECRET so no new .env variable is required
        secret = os.getenv("JWT_SECRET", "voicerx-fallback-secret")
        digest = hashlib.sha256(secret.encode()).digest()   # exactly 32 bytes
        key    = base64.urlsafe_b64encode(digest)           # Fernet needs b64url-encoded key

    return Fernet(key)


def encrypt_patient_id(patient_id: str) -> str:
    """
    Encrypts a plain-text patient ID and returns a URL-safe base64 token string.
    The result is safe to store in MongoDB / include in JSON responses.
    """
    if not patient_id or not patient_id.strip():
        raise ValueError("patient_id must not be empty")
    f = _get_fernet()
    encrypted_bytes = f.encrypt(patient_id.strip().encode("utf-8"))
    return encrypted_bytes.decode("utf-8")   # already URL-safe base64


def decrypt_patient_id(token: str) -> str:
    """
    Decrypts an encrypted patient ID token back to the original string.
    Raises cryptography.fernet.InvalidToken if tampered or wrong key.
    """
    if not token:
        raise ValueError("token must not be empty")
    f = _get_fernet()
    return f.decrypt(token.encode("utf-8")).decode("utf-8")
